- name: Post-installation workstation setup
  hosts: localhost
  vars_files:
    - defaults.yml

  roles:
    - role: egdoc.dotfiles
      tags: dotfiles

    - role: egdoc.vim
      tags: vim

    - role: egdoc.jetbrains
      tags: ide

    - role: geerlingguy.docker
      become: true
      tags: docker

  tasks:
    - name: Import GNOME tasks
      ansible.builtin.import_tasks:
        file: tasks/gnome.yml
      when: desktop_environment == "gnome"

    - name: Import Xfce tasks
      ansible.builtin.import_tasks:
        file: tasks/xfce.yml
      when: desktop_environment == "xfce"

    - name: Import Plasma tasks
      ansible.builtin.import_tasks:
        file: tasks/plasma.yml
      when: desktop_environment == "plasma"

    - name: Import packages tasks
      ansible.builtin.import_tasks:
        file: tasks/common-packages.yml
      tags: common-packages

    - name: Import google chrome tasks
      ansible.builtin.import_tasks:
        file: tasks/google-chrome.yml
      tags: google-chrome

    - name: Import vscode tasks
      ansible.builtin.import_tasks:
        file: tasks/vscode.yml
      tags: vscode

    - name: Import flatpak tasks
      ansible.builtin.import_tasks:
        file: tasks/flatpak.yml
      tags: flatpak

    - name: Import avatar tasks
      ansible.builtin.import_tasks:
        file: tasks/avatar.yml
      tags: avatar


  handlers:
    - name: Regenerate initramfs
      become: true
      ansible.builtin.command: dracut --regenerate-all --force

    - name: Ensure graphical.target is the default
      become: true
      ansible.builtin.command: systemctl set-default graphical.target
