- name: Install workstation packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - '@virtualization'
      - linux-firmware
      - ansible
      - ansible-collection-community-general
      - firefox
      - power-profiles-daemon
      - python3-pip
      - python3-psutil
      - python3-virtualenv
      - python3-jmespath
      - php-cli
      - composer
      - nodejs
      - npm
      - git
      - svn
      - pass
      - stow
      - lftp
      - nmap
      - ShellCheck
      - vim
      - sqlite
  when: "ansible_facts.distribution == 'Fedora'"
