- name: Ensure Docker packages are installed
  become: true
  ansible.builtin.package:
    state: latest
    name:
        - docker
        - docker-compose
  when: "ansible_facts.distribution == 'Fedora'"

- name: Install Docker-ce
  become: true
  block:
    - name: Ensure docker-ce key is in rpm database
      ansible.builtin.rpm_key:
        key: https://download.docker.com/linux/rhel/gpg
        fingerprint: 060A61C51B558A7F742B77AAC52FEB6B621E9F35

    - name: Ensure docker-ce repository is in place
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Ensure Docker packages are installed
      ansible.builtin.dnf:
        state: latest
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
  when: "ansible_facts.distribution in [ 'Rocky', 'Red Hat Enterprise Linux' ]"

- name: Ensure user is member of docker group
  become: true
  ansible.builtin.user:
    name: doc
    groups: docker
    append: true