- name: Install GNOME packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - '@Common NetworkManager Submodules'
      - '@Core'
      - '@Fedora Workstation product core'
      - '@Fonts'
      - '@GNOME'
      - '@Hardware Support'
      - '@Printing Support'
      - '@base-x'
      - python3-psutil
    exclude:
      - amd-gpu-firmware
      - nvidia-gpu-firmware
      - fedora-workstation-backgrounds
      - desktop-backgrounds-gnome
      - gamemode
      - gnome-shell-extension-background-logo
      - lrzsz
      - mediawriter
      - rhythmbox
      - toolbox
      - unoconv
      - gnome-boxes
      - gnome-connections
      - gnome-initial-setup
      - cheese
      - gnome-clocks
      - gnome-maps
      - gnome-photos
      - gnome-remote-desktop
      - gnome-themes-extra
      - gnome-weather
      - orca
      - rygel
      - totem
      - gnome-tour
  when: "ansible_facts.distribution == 'Fedora'"
  notify: Regenerate initramfs

- name: Setup dconf
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  loop:
    - { key: '/org/gnome/desktop/sound/event-sounds', value: 'false' }
    - { key: '/org/gnome/desktop/interface/show-battery-percentage', value: 'true' }
    - { key: '/org/gnome/desktop/peripherals/touchpad/natural-scroll', value: 'false' }
    - { key: '/org/gnome/desktop/peripherals/touchpad/tap-to-click', value: 'true' }
    - { key: '/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled', value: 'true' }
    - { key: '/org/gnome/desktop/privacy/remember-recent-files', value: 'false' }
    - { key: '/org/gnome/settings-daemon/plugins/media-keys/home', value: "['<Super>f']" }
    - { key: '/org/gnome/settings/daemon/plugins/media-keys/www', value: "['<Super>w']" }
    - { key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name', value: "'Launch terminal'" }
    - { key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command', value: "'gnome-terminal'" }
    - { key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding', value: "'<Super>Return'" }
    - { key: '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings', value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']" }
    - { key: '/org/gnome/TextEditor/indent-style', value: "'space'" }
    - { key: '/org/gnome/TextEditor/spellcheck', value: 'false' }
    - { key: '/org/gnome/TextEditor/tab-width', value: 'uint32 2' }
    - { key: '/org/gnome/TextEditor/wrap-text', value: 'false' }
    - { key: '/org/gnome/TextEditor/show-line-numbers', value: 'true' }
    - { key: '/org/gnome/nautilus/icon-view/default-zoom-level', value: "'standard'" }
    - { key: '/org/gnome/nautilus/icon-view/captions', value: "['permissions', 'none', 'none' ]" }
    - { key: '/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns', value: '150' }
    - { key: '/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows', value: '30' }
    - { key: '/org/gtk/gtk4/settings/file-chooser/sort-directories-first', value: 'true' }
    - { key: '/org/gtk/settings/file-chooser/sort-directories-first', value: 'true' }
    - { key: '/org/gnome/mutter/center-new-windows', value: 'true' }
    - { key: '/org/gnome/desktop/interface/monospace-font-name', value: "'Fira Code 10'" }
  tags: dconf

- name: Ensure GDM is enabled
  become: true
  ansible.builtin.systemd:
    name: gdm
    enabled: true
    force: true
  notify: Ensure graphical.target is the default