- name: Install Chrome
  become: true
  block:
    - name: Import Chrome gpg key
      ansible.builtin.rpm_key:
        key: https://dl.google.com/linux/linux_signing_key.pub
        fingerprint: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991

    - name: Ensure Google Chrome repository exists
      ansible.builtin.yum_repository:
        name: google-chrome
        description: google-chrome
        baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
        file: /etc/yum.repos.d/google-chrome
        enabled: true
        gpgcheck: true
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub

    - name: Install Chrome package
      ansible.builtin.dnf:
        name: google-chrome-stable
        state: present
  tags: 'google-chrome'