- name: Install Plasma packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - '@Common NetworkManager Submodules'
      - '@Core'
      - '@Fonts'
      - '@Hardware Support'
      - '@KDE'
      - '@Printing Support'
      - '@Standard'
      - '@base-x'
    exclude:
      - akregator
      - dnfdragora
      - firewall-config
      - gnome-keyring-pam
      - initial-setup-gui
      - kaddressbook
      - kamera
      - kde-partitionmanager
      - kdeplasma-addons
      - kmail
      - kmouth
      - kontact
      - korganizer
      - plasma-vault
      - xdg-desktop-portal-gnome
  when: "ansible_facts.distribution == 'Fedora'"
  notify: Regenerate initramfs

- name: Ensure sddm is enabled
  become: true
  ansible.builtin.systemd:
    name: sddm
    enabled: true
    force: true
  notify: Ensure graphical.target is the default