- name: Install Visual Studio Code
  become: true
  tags: vscode
  block:
    - name: Import Visual Studio Code key
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        fingerprint: 'BC528686B50D79E339D3721CEB3E94ADBE1229CF'

    - name: Ensure Visual Studio Code repository exists
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install Visual Studio Code
      ansible.builtin.dnf:
        name: code
        state: latest